fix persistency bug in the Python version
zopefoundation/BTrees pull request #147
Opened 2020-11-06 23:09 UTC by d-maurer

fixes #118

2020-11-07 00:00 UTC, mgedmin approved these changes
LGTM.

Do you think it would be hard to write a regression test for this case?

2020-11-07 00:02 UTC, mgedmin requested changes

2020-11-07 00:02 UTC, mgedmin commented on CHANGES.rst
> +  (`#118 https://github.com/zopefoundation/BTrees/issues/118`_).
This is invalid ReST syntax, which gets caught by our Mac OS jobs in Travis CI running `twine check`:

```
   `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 39: Error: Unknown target name: "#118 https://github.com/zopefoundation/btrees/issues/118".
```

You're missing the `<` `>` around the URL.

2020-11-07 05:44 UTC, d-maurer commented
Marius Gedminas wrote at 2020-11-6 16:02 -0800:
>@mgedmin requested changes on this pull request.
> ...
>You're missing the `<` `>` around the URL.

Thank you for this catch! Fixed.

2020-11-07 06:28 UTC, d-maurer commented
Marius Gedminas wrote at 2020-11-6 16:00 -0800:
>@mgedmin approved this pull request.
> ...
>Do you think it would be hard to write a regression test for this case?

The difficult part comes from the fact that only the Python implementation
is affected. Otherwise, a test would be simple:
construct a tree with 2 buckets; empty the second bucket;
commit (i.e. write to ZODB); reload; check.

Even when the C implementation is available, I can access
the Python implementation (via class names with `Py` suffix).
However, some magic seems to cause a class name change
which might affect storing and loading the tree
(I suppose that at least the C implementation classes are used
on reloading).

I can deactivate the C implmentation via the envvar `PURE_PYTHON`
(that's what I did in my manual test). However, the envvar
affects only the initial `BTrees` import. Therefore, this approach
is difficult in part of a test suite (where `BTrees` might
already have been imported for preceding tests).

I have seen in `tox.ini` that there are `*-pure` envs
which apparently set the envvar `PURE_PYTHON`.
But, the test above would require both `w_zodb` as well as
`-pure` and I have not seen a hint that they are available together.

2020-11-07 09:28 UTC, mgedmin commented
I don't think it would be good to target the pure-python implementation specifically; it'd be better to have a generic test for this case that gets run against both C and Python implementations.

We don't need to have a single test suite run cover all the implementations.  We have multiple CI jobs for a reason, and some of them run with PURE_PYTHON=1.

If we're missing a job with PURE_PYTHON and w_zodb in Travis CI, let's add one!  I don't particularly care about tox.ini, unless it would help writing that test to have an additional toxenv, in which case go right ahead!

2020-11-09 09:10 UTC, d-maurer commented
> If we're missing a job with PURE_PYTHON and w_zodb in Travis CI, let's add one! I don't particularly care about tox.ini, unless it would help writing that test to have an additional toxenv, in which case go right ahead!

I have added a test.

When I run the test in isolation (`PURE_PYTHON=1 python -m unittest discover -s BTrees -t . -p 'testPersist*.py'`) it correctly detects the problem (when the fix is not available) **BUT** `tox -e w_zodb-pure` does not. I suppose `tox` is not working as I expect: i.e. that a suffix `-pure` is not sufficient to get the envvar `PURE_PYTHON` set. Would be good if a `tox` expert could look into this.

2020-11-09 09:56 UTC, jugmac00 commented
I have no time to lookup the exact syntax, but my gut feeling tells me this should work:
```
[testenv:{py35,w_zodb}-pure]
setenv =
    PURE_PYTHON=1
```

If you want to look it up yourself, search for "tox factors".

2020-11-09 10:10 UTC, d-maurer commented
Jürgen Gmach wrote at 2020-11-9 01:57 -0800:
>I have no time to lookup the exact syntax, but my gut feeling tells me this should work:
>```
>[testenv:{py35,w_zodb}-pure]
>setenv =
>    PURE_PYTHON=1
>```
>
>If you want to look it up yourself, search for "tox factors".

The current `tox.ini` contains:
```
[testenv]
...
setenv =
  ...
  pure: PURE_PYTHON=1
```
As I understand the documentation this should work but apparently does not.


I am currently searching a way to convince `tox` to show the
environ variables it is using to executes the commands.
Even a large number of `-v` options does not do this.

2020-11-09 11:07 UTC, d-maurer commented
The problem was not a missing `PURE_PYTHON` envvar but a missing dependency.

I assumed that the `tox` env `w_zodb-pure` would inherit the settings of env `w_zodb`. This is not the case. As a consequence `w_zodb-pure` lacked the `ZODB` dependency and the test (which requires the ZODB) was skipped.

I made several trials to cover both `w_zodb` and `w_zodb-pure` in a single section -- all failing. Finally, I used a copy of the `w_zodb` section to define `w_zodb-pure`.

2020-11-09 15:41 UTC, mgedmin approved these changes
lgtm

2020-11-09 15:41 UTC, mgedmin commented on BTrees/tests/common.py
> +            del self.db
Why this rather than, say, `self.db = None`?

2020-11-09 15:42 UTC, mgedmin commented on tox.ini
> +    py27,py27-pure,py35,py35-pure,py36,py37,py38,pypy,pypy3,w_zodb,w_zodb-pure,coverage,docs
Do we have a .travis.yml job corresponding to this?

2020-11-09 15:43 UTC, mgedmin commented on tox.ini
> +    py27,py27-pure,py35,py35-pure,py36,py37,py38,pypy,pypy3,w_zodb,w_zodb-pure,coverage,docs
Yes, AFAICT _all_ of our Travis jobs include ZODB.

2020-11-09 18:04 UTC, d-maurer commented
Marius Gedminas wrote at 2020-11-9 07:41 -0800:
>@mgedmin approved this pull request.
>
>lgtm
>
>>      def tearDown(self):
>         if self.db is not None:
>             self.db.close()
>+            del self.db
>
>Why this rather than, say, `self.db = None`?

I wanted to restore the initial state (where `db` is defined
at class level). Of course `self.db = None` would have almost the same
effect.

2020-11-09 18:05 UTC, d-maurer commented
Marius Gedminas wrote at 2020-11-9 07:42 -0800:
>@mgedmin commented on this pull request.
>> @@ -3,7 +3,7 @@ envlist =
> # Jython support pending 2.7 support, due 2012-07-15 or so.  See:
> # http://fwierzbicki.blogspot.com/2012/03/adconion-to-fund-jython-27.html
> #   py27,jython,pypy,coverage,docs
>-    py27,py27-pure,py35,py35-pure,py36,py37,py38,pypy,pypy3,w_zodb,coverage,docs
>+    py27,py27-pure,py35,py35-pure,py36,py37,py38,pypy,pypy3,w_zodb,w_zodb-pure,coverage,docs
>
>Do we have a .travis.yml job corresponding to this?

I have still very few knowledge about travis
(and made my first steps with `tox`).

2020-11-09 21:51 UTC, mgedmin commented
> I wanted to restore the initial state (where `db` is defined
> at class level).

Ah!  I didn't realize that was the case

> Of course `self.db = None` would have almost the same effect.

and would maybe avoid a possible bug in the future if somebody moves the class attribute into `__init__` and doesn't realize they need to also update this code.

2020-11-10 05:55 UTC, d-maurer commented
Marius Gedminas wrote at 2020-11-9 13:51 -0800:
> ...
>and would maybe avoid a possible bug in the future if somebody moves the class attribute into `__init__` and doesn't realize they need to also update this code.

This is a `unittest.TestCase` class. Its `__init__` is (mostly) private
(and called for each individual test). Thus, there is no danger.

In fact, I added the `del` (only) to help me interactively debug why my test
(initially) did not reveal the problem. It is not important for
the real test suite (you can delete it if you like).

As to the problem: the persistency loophole is very small:
it affects only the case that a transaction deletes the last
item in a bucket without having previously deleted anything in this
bucket. My initial test had emptied the whole bucket in the same
transaction and this did not reproduce the problem.

2020-11-10 06:26 UTC, mgedmin commented
> This is a `unittest.TestCase` class. 

I should stop reviewing code when I'm tired.  I didn't even notice that!

I retract my comments on this.

2020-11-11 05:38 UTC, merged