allow build documentatiomn without have `BTrees` module installed
zopefoundation/BTrees pull request #194
Opened 2023-09-25 21:19 UTC by kloczek

This patch allow build documentation without have `BTrees` module installed.
It has been mentioned in #180.

2023-09-29 06:10 UTC, icemac requested changes
`pkg_resources` is deprecated, so we should solve the issue without using it any more.

2023-09-29 07:58 UTC, kloczek commented
> `pkg_resources` is deprecated, so we should solve the issue without using it any more.

Yep .. but that is another issue 😄

2024-03-01 07:42 UTC, icemac commented
Okay, we can replace `pkg_resources` later.

According to the contributing policies of the zopefoundation organization you need to sign a contributor agreement before any non-trivial change can be merged. For details please consult the [Contributing guidelines for zopefoundation projects](https://github.com/zopefoundation/.github/blob/master/CONTRIBUTING.md).

2024-03-01 11:10 UTC, kloczek commented
I would suggest use `packaging-sphinx` https://sphinx-packaging.readthedocs.io/en/latest/

2024-05-30 13:02 UTC, kloczek commented
> According to the contributing policies of the zopefoundation organization you need to sign a contributor agreement before any non-trivial change can be merged. For details please consult the [Contributing guidelines for zopefoundation projects](https://github.com/zopefoundation/.github/blob/master/CONTRIBUTING.md).

I found only pdf with form to sign.
Is there any online sing form? 🤔

2024-06-03 06:02 UTC, icemac commented
@kloczek There is only the PDF form. If you have a PDF editor (like Apples Preview.app) to fill it out you can do it paperless.

2024-06-03 06:33 UTC, kloczek commented
I'm not using Apple (only Linux)

2024-08-15 07:10 UTC, icemac commented
Is there any progress with the contributor agreement, so the PR can get merged?

2024-08-26 16:00 UTC, tseaver commented
@icemac I do not believe that this PR contains any copyrightable changes:  moving one import and adding `src/` to the `sys.path` entries are trivial / non-original in terms of what copyright protects.

2024-08-27 06:36 UTC, icemac approved these changes

2024-08-27 15:16 UTC, closed without merging

2024-08-27 15:16 UTC, tseaver commented
@kloczek Thanks for your efforts!

This PR is no longer relevant after the application of the current `meta` templating to `docs/conf.py` (PR #211).

2024-08-28 14:13 UTC, kloczek commented
Thank you 👍